# Generated by Django 5.1.6 on 2026-03-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("payment_success", "Payment Success"),
                    ("order_shipped", "Order Shipped"),
                    ("order_delivered", "Order Delivered"),
                    ("order_cancelled", "Order Cancelled"),
                    ("refund_completed", "Refund Completed"),
                    ("low_stock_alert", "Low Stock Alert"),
                    ("new_order", "New Order"),
                    ("payment_confirmed", "Payment Confirmed"),
                    ("product_sold", "Product Sold"),
                    ("commission_created", "Commission Created"),
                    ("commission_approved", "Commission Approved"),
                ],
                max_length=50,
            ),
        ),
    ]
