# Generated by Django 5.1.6 on 2026-03-21 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_fix_legacy_shop_uuid_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shop",
            name="marketers",
        ),
    ]
