# Generated by Django 5.1.6 on 2026-03-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0013_remove_user_merchant_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="base_price",
        ),
        migrations.RemoveField(
            model_name="user",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="user",
            name="followers_count",
        ),
        migrations.RemoveField(
            model_name="user",
            name="instagram",
        ),
        migrations.RemoveField(
            model_name="user",
            name="marketer_commission",
        ),
        migrations.RemoveField(
            model_name="user",
            name="marketer_type",
        ),
        migrations.RemoveField(
            model_name="user",
            name="pricing_type",
        ),
        migrations.RemoveField(
            model_name="user",
            name="services",
        ),
        migrations.RemoveField(
            model_name="user",
            name="team_size",
        ),
        migrations.RemoveField(
            model_name="user",
            name="tiktok",
        ),
        migrations.RemoveField(
            model_name="user",
            name="website",
        ),
        migrations.RemoveField(
            model_name="user",
            name="youtube",
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("CUSTOMER", "Customer"),
                    ("SHOP_OWNER", "Shop Owner"),
                    ("SUPPLIER", "Supplier"),
                    ("COURIER", "Courier"),
                ],
                default="CUSTOMER",
                max_length=20,
            ),
        ),
    ]
