# Generated by Django 6.0.2 on 2026-05-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_remove_user_base_price_remove_user_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('SHOP_OWNER', 'Shop Owner'), ('SUPPLIER', 'Supplier'), ('COURIER', 'Courier'), ('MARKETER', 'Marketer')], default='CUSTOMER', max_length=20),
        ),
    ]
