# Generated by Django 5.1.6 on 2026-03-21 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MarketerDailyAnalytics",
        ),
    ]
