# Generated by Django 5.1.6 on 2026-03-22 09:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0002_follow"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostLike",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="hub.post",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_likes",
                        to="hub.profile",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["post", "created_at"],
                        name="hub_postlik_post_id_c1f212_idx",
                    ),
                    models.Index(
                        fields=["profile", "created_at"],
                        name="hub_postlik_profile_d3ccee_idx",
                    ),
                ],
                "unique_together": {("post", "profile")},
            },
        ),
    ]
