# Generated by Django 5.1.6 on 2026-03-27 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "courier",
            "0002_rename_courier_shi_status_03d7de_idx_courier_shi_status_61b857_idx_and_more",
        ),
        ("order", "0004_order_delivery_method"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CourierProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("BIKE", "Bike"),
                            ("CAR", "Car"),
                            ("VAN", "Van"),
                            ("TRUCK", "Truck"),
                            ("OTHER", "Other"),
                        ],
                        default="BIKE",
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courier_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_available", "user_id"],
            },
        ),
        migrations.RemoveIndex(
            model_name="shipment",
            name="courier_shi_externa_4dc88b_idx",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="external_shipment_id",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="external_tracking_id",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="courier",
        ),
        migrations.AddField(
            model_name="shipment",
            name="assigned_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="courier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_shipments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PICKED_UP", "Picked Up"),
                    ("IN_TRANSIT", "In Transit"),
                    ("OUT_FOR_DELIVERY", "Out for Delivery"),
                    ("DELIVERED", "Delivered"),
                    ("FAILED", "Failed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(
                fields=["courier", "status"], name="courier_shi_courier_becbaa_idx"
            ),
        ),
        migrations.DeleteModel(
            name="CourierPartner",
        ),
    ]
